[build]
  publish   = "."
  functions = "netlify/functions"

  # Rulează pe Node 20 (ok pentru Twilio v5 + Supabase v2)
  [build.environment]
    NODE_VERSION = "20"

[functions]
  # Folosim esbuild (rapid) și lăsăm pachetele grele externe
  node_bundler = "esbuild"
  external_node_modules = ["twilio", "@supabase/supabase-js"]

# ------------------ Redirects / Rewrites ------------------

# Proxy API simplu: /api/* -> /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# Shortcut pentru chat (folosit în index/chatbot): /chat -> funcția „chat”
[[redirects]]
  from = "/chat"
  to   = "/.netlify/functions/chat"
  status = 200

# Asigură servirea directă a callback-ului de autentificare (fără fallback SPA)
[[redirects]]
  from = "/auth-callback"
  to   = "/auth-callback.html"
  status = 200

# (opțional) SPA fallback – păstrează-l la final ca „catch-all”
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# ------------------ Headers (Cache & Security) ------------------

# Cache agresiv pentru asset-uri statice fingerprintable
[[headers]]
  for = "/**/*.@(css|js|png|jpg|jpeg|gif|webp|svg|ico|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML: no-store (îți lasă loc pentru deploy-uri instant fără cache vechi)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store"

# Minimal security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# ⚠️ CSP rezonabilă pentru ce folosești (Supabase CDN, jsDelivr, Google Fonts).
# Dacă OAuth sau un provider social mai necesită domenii suplimentare,
# adaugă-le la `connect-src` / `frame-src` și reîncercă.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      base-uri   'self';
      img-src    'self' data: blob: https:;
      style-src  'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src   'self' https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net;
      connect-src 'self' https://*.supabase.co https://*.supabase.in /.netlify/functions/ /api/;
      frame-src  https://*.supabase.co https://accounts.google.com https://appleid.apple.com https://www.facebook.com;
      object-src 'none';
      frame-ancestors 'self';
      upgrade-insecure-requests;
    """