[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["twilio","@supabase/supabase-js"]

# ---------- HEADERS (CSP) ----------
# Setăm Content-Security-Policy la nivel de server (recomandat).
# IMPORTANT: După ce activezi asta, elimină orice <meta http-equiv="Content-Security-Policy"> din HTML,
# ca să nu intre în conflict cu headerul.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.supabase.in wss://*.supabase.in https://verify.twilio.com https://api.twilio.com;
      img-src 'self' data: https:;
      script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline';
      style-src  'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
      font-src 'self' https://fonts.gstatic.com data:;
      frame-ancestors 'self';
      base-uri 'self';
    """

# ---------- Redirecturi ----------
# Proxy API -> Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# (opțional) fallback pentru SPA — dacă vrei ca toate rutele necunoscute să trimită la index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200