[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["twilio","@supabase/supabase-js"]

# ===== Securitate: Content-Security-Policy + alte headere
[[headers]]
  for = "/*"
  [headers.values]
    # IMPORTANT: nu mai pune surse relative (ex: "/api/*") în CSP.
    # 'self' acoperă toate apelurile către /.netlify/functions/*.
    Content-Security-Policy = """
      default-src 'self';
      script-src  'self' https://cdn.jsdelivr.net https://cdn.jsdelivr.net/npm/@supabase/supabase-js https://unpkg.com;
      connect-src 'self' https://*.supabase.co https://api.netlify.com https://verify.twilio.com https://*.twilio.com data: blob:;
      style-src   'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com;
      font-src    'self' https://fonts.gstatic.com data:;
      img-src     'self' data: blob:;
      frame-ancestors 'self';
      base-uri 'self';
      form-action 'self';
    """
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"
    Permissions-Policy     = "geolocation=(), microphone=(), camera=()"
    X-Frame-Options        = "SAMEORIGIN"

# Proxy API -> Functions (poți folosi /api/* dacă vrei, dar nu-l include în CSP)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# (opțional) fallback pentru SPA — păstrează doar dacă site-ul e 100% SPA
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200