[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  # folosim esbuild pentru bundle
  node_bundler          = "esbuild"
  external_node_modules = ["twilio", "@supabase/supabase-js"]

# ---------- Redirects API → Functions ----------
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200

# ---------- SPA fallback ----------
# Toate rutele ne-rezolvate merg către index.html,
# dar exclude explicit folderele statice /api și /assets
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200