[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# (păstrează redirecțiile dacă le folosești)
[[redirects]]
  from = "/chat"
  to   = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
