[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Map /chat -> funcția serverless
[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
