[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["twilio","@supabase/supabase-js"]

# Proxy API -> Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# (opțional) fallback pentru SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
